version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ../../app/static:/app/static
      - ../../app/media:/app/media
    depends_on:
      - "app"

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always

  app:
    container_name: app
    build: ../..
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=134.209.255.12
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - ../../app:/code
    ports:
      - "8015:8000"
    links:
      - postgres
    depends_on:
      - "postgres"
      - "redis"
      - "selenium"

  postgres:
    container_name:  postgres-db
    image:           postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env

  redis:
    build:
      context: ../..
      dockerfile: redis.dockerfile
    image: redis:4.0.11
    restart: "on-failure"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env

  celery:
    restart: "always"
    build:
      context: ../..
      dockerfile: celery.dockerfile
    container_name: celery
    environment:
      - CELERY_BROKER_URL='redis://redis:6379/0'
      - CELERY_RESULT_BACKEND='redis://redis:6379/0'
      - BROKER_URL='redis://:dKqs72RhtaPPYyfN@redis:6379/0'
    command: celery --app=app.celery:app worker -B --loglevel=INFO
    volumes:
      - ../../app:/code
    links:
      - redis
      - postgres
    depends_on:
      - "redis"
      - "postgres"

networks:
  default:
    external:
      name: nginx-proxy
