# Generated by Django 4.1.5 on 2023-01-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated date')),
                ('order_number', models.CharField(db_index=True, max_length=255, verbose_name='sifariş nömrəsi')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='sifariş tarixi')),
                ('order_receiver', models.CharField(max_length=255, verbose_name='alıcı')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.account', verbose_name='müştəri')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated date')),
                ('package_number', models.CharField(db_index=True, max_length=255, verbose_name='bağlama nömrəsi')),
                ('cargo_company', models.CharField(max_length=255, verbose_name='karqo firması')),
                ('tracking_number', models.CharField(max_length=255, verbose_name='Kargo takip numarası')),
                ('category', models.CharField(max_length=255, verbose_name='Kateqoriya')),
                ('price', models.CharField(max_length=255, verbose_name='Qiymət')),
                ('product_count', models.CharField(max_length=255, verbose_name='Məhsul sayı')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.delivery', verbose_name='sifariş')),
            ],
            options={
                'verbose_name': 'Bağlama',
                'verbose_name_plural': 'Bağlamalar',
            },
        ),
    ]
