# Generated by Django 4.1.5 on 2023-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sifariş tarixi'),
        ),
    ]
