# Generated by Django 4.1.5 on 2023-02-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_slug'),
        ('delivery', '0002_alter_delivery_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveries', to='core.account', verbose_name='müştəri'),
        ),
    ]
