# Generated by Django 4.1.5 on 2023-02-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-created_at',), 'verbose_name': 'Bağlama', 'verbose_name_plural': 'Bağlamalar'},
        ),
    ]
