# Generated by Django 4.1.5 on 2023-02-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_package_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packages', to='delivery.delivery', verbose_name='sifariş'),
        ),
    ]
