# Generated by Django 4.1.5 on 2023-02-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_package_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Bağlama', 'verbose_name_plural': 'Bağlamalar'},
        ),
    ]
