# Generated by Django 4.1.5 on 2023-02-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_slug'),
        ('delivery', '0006_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='packages', to='core.account', verbose_name='müştəri'),
        ),
    ]
