# Generated by Django 4.1.5 on 2023-02-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_package_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='done',
            field=models.BooleanField(default=False, verbose_name='bitib'),
        ),
    ]
