# Generated by Django 4.1.5 on 2023-09-02 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_package_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
    ]
