# Generated by Django 4.1.5 on 2023-01-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated date')),
                ('client_id', models.CharField(max_length=255, verbose_name='Müştəri ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Şifrə')),
                ('is_processing', models.BooleanField(default=False, verbose_name='Proses gedir')),
            ],
            options={
                'verbose_name': 'Müştəri',
                'verbose_name_plural': 'Müştərilər',
            },
        ),
    ]
