# Generated by Django 4.1.5 on 2023-01-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Proses gedib'),
        ),
    ]
