# Generated by Django 4.1.5 on 2023-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Proses vaxtı'),
        ),
    ]
