# Generated by Django 4.1.5 on 2023-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Müştəri ID'),
        ),
    ]
