# Generated by Django 4.1.5 on 2023-02-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
