# Generated by Django 4.1.5 on 2023-08-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_excelldeclinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excellasaninfo',
            options={'verbose_name': 'Asan login Excell fayl', 'verbose_name_plural': 'Asan login Excell fayllar'},
        ),
        migrations.AlterModelOptions(
            name='excelldeclinfo',
            options={'verbose_name': 'Deklarasiya Excell fayl', 'verbose_name_plural': 'Deklarasiya Excell fayllar'},
        ),
    ]
