# Generated by Django 4.1.5 on 2023-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_excellasaninfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excellasaninfo",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="excell_asan_info",
                verbose_name="Excell fayl",
            ),
        ),
        migrations.AlterField(
            model_name="excelldeclinfo",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="excell_decl_info",
                verbose_name="Excell fayl",
            ),
        ),
    ]
