# Generated by Django 4.1.5 on 2023-08-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_excellasaninfo_file_alter_excelldeclinfo_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedDeclar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated date"
                    ),
                ),
                ("fin_code", models.CharField(max_length=255, verbose_name="Fin kod")),
                ("password", models.CharField(max_length=255, verbose_name="Şifrə")),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="İstifadəçi ID"),
                ),
                (
                    "dec_id",
                    models.CharField(max_length=255, verbose_name="Göndəriş ID"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Uğursuz deklarasiya",
                "verbose_name_plural": "Uğursuz deklarasiyalar",
            },
        ),
    ]
