# Generated by Django 4.1.5 on 2023-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_faileddeclar"),
    ]

    operations = [
        migrations.AddField(
            model_name="faileddeclar",
            name="reason",
            field=models.CharField(
                default="hech ne", max_length=255, verbose_name="Səbəb"
            ),
            preserve_default=False,
        ),
    ]
