# Generated by Django 4.1.5 on 2023-09-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_faileddeclar_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='excellasaninfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='excellasaninfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='excelldeclinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='excelldeclinfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='faileddeclar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faileddeclar',
            name='updated_at',
        ),
    ]
