# Generated by Django 4.1.5 on 2023-09-02 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_account_created_at_remove_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='excellasaninfo',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='excelldeclinfo',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='faileddeclar',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date'),
        ),
    ]
