# Generated by Django 4.1.5 on 2023-09-06 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_account_created_at_excellasaninfo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('fin_code', models.CharField(max_length=255, verbose_name='Fin kod')),
                ('password', models.CharField(max_length=255, verbose_name='Şifrə')),
                ('user_id', models.CharField(max_length=255, verbose_name='İstifadəçi ID')),
                ('dec_id', models.CharField(max_length=255, verbose_name='Göndəriş ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
