# Generated by Django 4.1.5 on 2023-09-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='dec_id',
            field=models.CharField(max_length=255, verbose_name='Declaration ID'),
        ),
    ]
