# Generated by Django 4.1.5 on 2023-09-07 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_declaration_dec_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('start_interval', models.IntegerField(default=0, verbose_name='Start Interval')),
                ('end_interval', models.IntegerField(default=0, verbose_name='End Interval')),
            ],
            options={
                'verbose_name': 'Interval',
                'verbose_name_plural': 'Intervals',
            },
        ),
    ]
