# Generated by Django 4.1.5 on 2023-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
