# Generated by Django 4.1.5 on 2023-09-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_interval_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='is_declared',
            field=models.BooleanField(default=False, verbose_name='Bəyan olunub'),
        ),
    ]
